# Generated by Django 4.2.4 on 2023-10-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(max_length=100)),
            ],
        ),
    ]
